// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "lgbk": Application User Types
//
// Command:
// $ goagen
// --design=github.com/yuuu/lgbk-api/design
// --out=$(GOPATH)/src/github.com/yuuu/lgbk-api
// --version=v1.3.1

package client
