// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "lgbk": Application Controllers
//
// Command:
// $ goagen
// --design=github.com/yuuu/lgbk-api/design
// --out=$(GOPATH)/src/github.com/yuuu/lgbk-api
// --version=v1.3.1

package app

import (
	"context"
	"github.com/goadesign/goa"
	"net/http"
)

// initService sets up the service encoders, decoders and mux.
func initService(service *goa.Service) {
	// Setup encoders and decoders
	service.Encoder.Register(goa.NewJSONEncoder, "application/json")
	service.Encoder.Register(goa.NewGobEncoder, "application/gob", "application/x-gob")
	service.Encoder.Register(goa.NewXMLEncoder, "application/xml")
	service.Decoder.Register(goa.NewJSONDecoder, "application/json")
	service.Decoder.Register(goa.NewGobDecoder, "application/gob", "application/x-gob")
	service.Decoder.Register(goa.NewXMLDecoder, "application/xml")

	// Setup default encoder and decoder
	service.Encoder.Register(goa.NewJSONEncoder, "*/*")
	service.Decoder.Register(goa.NewJSONDecoder, "*/*")
}

// DateController is the controller interface for the Date actions.
type DateController interface {
	goa.Muxer
	Index(*IndexDateContext) error
	Show(*ShowDateContext) error
}

// MountDateController "mounts" a Date resource controller on the given service.
func MountDateController(service *goa.Service, ctrl DateController) {
	initService(service)
	var h goa.Handler

	h = func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		// Check if there was an error loading the request
		if err := goa.ContextError(ctx); err != nil {
			return err
		}
		// Build the context
		rctx, err := NewIndexDateContext(ctx, req, service)
		if err != nil {
			return err
		}
		return ctrl.Index(rctx)
	}
	h = handleSecurity("basic_auth", h)
	service.Mux.Handle("GET", "/dates/", ctrl.MuxHandler("index", h, nil))
	service.LogInfo("mount", "ctrl", "Date", "action", "Index", "route", "GET /dates/", "security", "basic_auth")

	h = func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		// Check if there was an error loading the request
		if err := goa.ContextError(ctx); err != nil {
			return err
		}
		// Build the context
		rctx, err := NewShowDateContext(ctx, req, service)
		if err != nil {
			return err
		}
		return ctrl.Show(rctx)
	}
	h = handleSecurity("basic_auth", h)
	service.Mux.Handle("GET", "/dates/:dateID", ctrl.MuxHandler("show", h, nil))
	service.LogInfo("mount", "ctrl", "Date", "action", "Show", "route", "GET /dates/:dateID", "security", "basic_auth")
}
