// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "lgbk": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/yuuu/lgbk-api/design
// --out=$(GOPATH)/src/github.com/yuuu/lgbk-api
// --version=v1.3.1

package app

import (
	"fmt"
	"strings"
)

// DateHref returns the resource href.
func DateHref(dateID interface{}) string {
	paramdateID := strings.TrimLeftFunc(fmt.Sprintf("%v", dateID), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/dates/%v", paramdateID)
}
